name: Test

on: 
  push:
    branches: [master, canary]
  pull_request:
  workflow_dispatch:

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@kalidao'
        cache: 'yarn'
    - name: Yarn
      run: yarn install --frozen-lockfile
    - name: Compile
      run: yarn build
    - name: Test 
      run: yarn test
